#!/usr/bin/python3

print('Content-type: text/html\n\n')
print('<html>')
print('<head>')
print('<title>RC 2</title>')
print('<link rel="stylesheet" href="css/bulma.css"')
print('</head>')
print('<body>')
print('<div class="container">')
print('<h1 class="title has-text-centered">Aplicacao CGI desenvolvida com python para a disciplina de redes 2</h1>')
print('<img src="imgs/img1.jpg">')
print('<img src="imgs/postgres.png">')
print('<img src="imgs/python.png">')
print('<a class="button is-link" href="http://localhost/redes2/connection.py">PostgreSQL Test Connection</a>')
print('<a class="button is-link" href="http://localhost/redes2/admin.sh">Admin</a>')
print('</div>')
print('</body>')
print('</html>')